### ISSUE TITLE
Предложения по работе

### ISSUE THREAD

**Issue by acoustic925** [Dimonix-mw/AvitoConsole#1]
Отличная работа, мне очень понравилось решение с optionsbuilder и .migrate.

Хотел бы предложить небольшие стилистические идеи, которые могут, как мне кажется улучшить читаемость и проверку кода.

Я бы предложил разнести методы из класса Program, по нескольким условно назовем их "сервисам", по их ответственности. 
Например взять все функции работы с консолью и поместить их в какой-нибудь ConsoleService, а функции работы с БД в например XXXDataService, а затем эти сервисы инжектить и использовать данный функционал через них, чтобы разделить ответственность, которая сейчас сосредоточена в классе Program. Это хорошая практика, разделять ответственность)

В остальном работа очень понравилась, очень аккуратная)
Спасибо за внимание!

**Comment by Dimonix-mw** [comment]
Спасибо за предложение.
